import { Enemy } from "../models/characters"
import { nanoid } from "nanoid"
export const enemies: Enemy[] = [
  {
    "id": nanoid(),
    "name": "Goblin Grunt",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 80,
    "maxHp": 80,
    "lvl": 1,
    "luck": 5,
    "arrmor": 2,
    "attackSpeed": 1,
    "evasion": 2,
    "damage": 12
  },
  {
    "id": nanoid(),
    "name": "Cave Spider",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 60,
    "maxHp": 60,
    "lvl": 2,
    "luck": 7,
    "arrmor": 1,
    "attackSpeed": 3,
    "evasion": 5,
    "damage": 8
  },
  {
    "id": nanoid(),
    "name": "Forest Troll",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 120,
    "maxHp": 120,
    "lvl": 3,
    "luck": 2,
    "arrmor": 4,
    "attackSpeed": 1,
    "evasion": 1,
    "damage": 15
  },
  {
    "id": nanoid(),
    "name": "Shadow Wraith",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 90,
    "maxHp": 90,
    "lvl": 4,
    "luck": 12,
    "arrmor": 0,
    "attackSpeed": 4,
    "evasion": 8,
    "damage": 14
  },
  {
    "id": nanoid(),
    "name": "Fire Imp",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 70,
    "maxHp": 70,
    "lvl": 2,
    "luck": 10,
    "arrmor": 1,
    "attackSpeed": 2,
    "evasion": 3,
    "damage": 13
  },
  {
    "id": nanoid(),
    "name": "Swamp Serpent",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 110,
    "maxHp": 110,
    "lvl": 3,
    "luck": 6,
    "arrmor": 3,
    "attackSpeed": 2,
    "evasion": 4,
    "damage": 17
  },
  {
    "id": nanoid(),
    "name": "Ice Golem",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 150,
    "maxHp": 150,
    "lvl": 5,
    "luck": 4,
    "arrmor": 6,
    "attackSpeed": 1,
    "evasion": 0,
    "damage": 20
  },
  {
    "id": nanoid(),
    "name": "Venomous Bat",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 50,
    "maxHp": 50,
    "lvl": 1,
    "luck": 8,
    "arrmor": 0,
    "attackSpeed": 5,
    "evasion": 10,
    "damage": 9
  },
  {
    "id": nanoid(),
    "name": "Lava Beast",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 130,
    "maxHp": 130,
    "lvl": 4,
    "luck": 3,
    "arrmor": 5,
    "attackSpeed": 2,
    "evasion": 2,
    "damage": 18
  },
  {
    "id": nanoid(),
    "name": "Dark Sorcerer",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 100,
    "maxHp": 100,
    "lvl": 3,
    "luck": 15,
    "arrmor": 1,
    "attackSpeed": 3,
    "evasion": 6,
    "damage": 16
  },
  {
    "id": nanoid(),
    "name": "Thunder Beast",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 140,
    "maxHp": 140,
    "lvl": 5,
    "luck": 7,
    "arrmor": 4,
    "attackSpeed": 2,
    "evasion": 3,
    "damage": 21
  },
  {
    "id": nanoid(),
    "name": "Ancient Treant",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 200,
    "maxHp": 200,
    "lvl": 6,
    "luck": 2,
    "arrmor": 8,
    "attackSpeed": 1,
    "evasion": 1,
    "damage": 25
  },
  {
    "id": nanoid(),
    "name": "Plague Rat",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 40,
    "maxHp": 40,
    "lvl": 1,
    "luck": 10,
    "arrmor": 0,
    "attackSpeed": 4,
    "evasion": 7,
    "damage": 6
  },
  {
    "id": nanoid(),
    "name": "Crystal Guardian",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 180,
    "maxHp": 180,
    "lvl": 5,
    "luck": 3,
    "arrmor": 7,
    "attackSpeed": 1,
    "evasion": 2,
    "damage": 22
  },
  {
    "id": nanoid(),
    "name": "Necrotic Revenant",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 160,
    "maxHp": 160,
    "lvl": 5,
    "luck": 5,
    "arrmor": 3,
    "attackSpeed": 2,
    "evasion": 4,
    "damage": 19
  }
]
