import { Enemy } from "../models/characters"
import { nanoid } from "nanoid"
import { items } from "./items"
export const enemies: Enemy[] = [
  {
    "id": nanoid(),
    "name": "Goblin Grunt",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monsters/18.png",
    "hp": 80,
    "maxHp": 80,
    "lvl": 1,
    "luck": 5,
    "arrmor": 2,
    "attackSpeed": 1,
    "evasion": 2,
    "damage": 12,
    "exp": 50,
    "gold": 10,
    "item": items[1]
  },
  {
    "id": nanoid(),
    "name": "Cave Spider",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monsters/21.png",
    "hp": 60,
    "maxHp": 60,
    "lvl": 2,
    "luck": 7,
    "arrmor": 1,
    "attackSpeed": 3,
    "evasion": 5,
    "damage": 8,
    "exp": 50,
    "gold": 10,
    "item": items[1]
  },
  {
    "id": nanoid(),
    "name": "Forest Troll",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monsters/29.png",
    "hp": 120,
    "maxHp": 120,
    "lvl": 3,
    "luck": 2,
    "arrmor": 4,
    "attackSpeed": 1,
    "evasion": 1,
    "damage": 15,
    "exp": 50,
    "gold": 10,
    "item": items[1]
  },
  {
    "id": nanoid(),
    "name": "Shadow Wraith",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monsters/38.png",
    "hp": 90,
    "maxHp": 90,
    "lvl": 4,
    "luck": 12,
    "arrmor": 0,
    "attackSpeed": 4,
    "evasion": 8,
    "damage": 14,
    "exp": 50,
    "gold": 10,
    "item": items[1]
  },
  {
    "id": nanoid(),
    "name": "Fire Imp",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monsters/60.png",
    "hp": 70,
    "maxHp": 70,
    "lvl": 2,
    "luck": 10,
    "arrmor": 1,
    "attackSpeed": 2,
    "evasion": 3,
    "damage": 13,
    "exp": 50,
    "gold": 10,
    "item": items[1]
  },
  {
    "id": nanoid(),
    "name": "Swamp Serpent",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monsters/64.png",
    "hp": 110,
    "maxHp": 110,
    "lvl": 3,
    "luck": 6,
    "arrmor": 3,
    "attackSpeed": 2,
    "evasion": 4,
    "damage": 17,
    "exp": 50,
    "gold": 10,
    "item": items[1]
  },
  {
    "id": nanoid(),
    "name": "Ice Golem",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monsters/66.png",
    "hp": 150,
    "maxHp": 150,
    "lvl": 5,
    "luck": 4,
    "arrmor": 6,
    "attackSpeed": 1,
    "evasion": 0,
    "damage": 20,
    "exp": 50,
    "gold": 10,
    "item": items[1]
  },
  {
    "id": nanoid(),
    "name": "Venomous Bat",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monsters/79.png",
    "hp": 50,
    "maxHp": 50,
    "lvl": 1,
    "luck": 8,
    "arrmor": 0,
    "attackSpeed": 5,
    "evasion": 10,
    "damage": 9,
    "exp": 50,
    "gold": 10,
    "item": items[1]
  },
  {
    "id": nanoid(),
    "name": "Lava Beast",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monsters/96.png",
    "hp": 130,
    "maxHp": 130,
    "lvl": 4,
    "luck": 3,
    "arrmor": 5,
    "attackSpeed": 2,
    "evasion": 2,
    "damage": 18,
    "exp": 50,
    "gold": 10,
    "item": items[1]
  },
  {
    "id": nanoid(),
    "name": "Dark Sorcerer",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 100,
    "maxHp": 100,
    "lvl": 3,
    "luck": 15,
    "arrmor": 1,
    "attackSpeed": 3,
    "evasion": 6,
    "damage": 16,
    "exp": 50,
    "gold": 10,
    "item": items[1]
  },
  {
    "id": nanoid(),
    "name": "Thunder Beast",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 140,
    "maxHp": 140,
    "lvl": 5,
    "luck": 7,
    "arrmor": 4,
    "attackSpeed": 2,
    "evasion": 3,
    "damage": 21,
    "exp": 50,
    "gold": 10,
    "item": items[1]
  },
  {
    "id": nanoid(),
    "name": "Ancient Treant",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 200,
    "maxHp": 200,
    "lvl": 6,
    "luck": 2,
    "arrmor": 8,
    "attackSpeed": 1,
    "evasion": 1,
    "damage": 25,
    "exp": 50,
    "gold": 10,
    "item": items[1]
  },
  {
    "id": nanoid(),
    "name": "Plague Rat",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 40,
    "maxHp": 40,
    "lvl": 1,
    "luck": 10,
    "arrmor": 0,
    "attackSpeed": 4,
    "evasion": 7,
    "damage": 6,
    "exp": 50,
    "gold": 10,
    "item": items[0]
  },
  {
    "id": nanoid(),
    "name": "Crystal Guardian",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 180,
    "maxHp": 180,
    "lvl": 5,
    "luck": 3,
    "arrmor": 7,
    "attackSpeed": 1,
    "evasion": 2,
    "damage": 22,
    "exp": 50,
    "gold": 10,
    "item": items[0]
  },
  {
    "id": nanoid(),
    "name": "Necrotic Revenant",
    "position": { "x": Math.floor(Math.random() * 80), "y": Math.floor(Math.random() * 80) },
    "model": "./monster.png",
    "hp": 160,
    "maxHp": 160,
    "lvl": 5,
    "luck": 5,
    "arrmor": 3,
    "attackSpeed": 2,
    "evasion": 4,
    "damage": 19,
    "exp": 50,
    "gold": 10,
    "item": items[1]
  }
]
